version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - CHOKIDAR_USEPOLLING= "true"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
      - ./backend/node_modules:/home/node/app/node_modules
    depends_on:
      - db
    command: npm run dev
    networks:
      - app-network

  # debugging lama ini kurang woey astaga
  migration: 
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
    depends_on:
      - db
    command: ["npx", "prisma", "migrate", "dev"]
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
      - ./frontend/node_modules:/home/node/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge
